### ISSUE TITLE
Code Refactor 

### ISSUE THREAD

**Issue by inferno46n2** [GSeanCDAT/GIMM-VFI#3]
This is amazing and thank you!

is there a planned code refactor / clean up? 80+ reqs is most def overkill and the code has a lot of redundancy.

Would be awesome to have this cleaned up as this is the best interpolation tool likely on the market.

**Comment by GSeanCDAT** [comment]
Hi! Thank you for your interest in our work. We’ll be including code cleanup in our next update, along with the release of the training code. Please stay tuned! 😊

**Comment by GSeanCDAT** [comment]
Thanks kijai for creating the nice ComfyUI version of our work :)

**Comment by GSeanCDAT** [comment]
The code has been cleaned and released alongside the training code. For the environmental requirements for inference, please refer to @kijai 's nice repo :)
