### ISSUE TITLE
system requirements?

### ISSUE THREAD

**Issue by WNnitro** [GSeanCDAT/GIMM-VFI#4]

**Comment by GSeanCDAT** [comment]
Hi, GPU resources are required. 
Our work is developed and tested with Nvidia V100 GPUs. In practice, GIMM-VFI can be run on most Nvidia GPUs, but it usually requires larger GPU memory when interpolating frames with higher resolution. 
You can set a smaller ```DS_SCALE``` to reduce the memory usage if encountering OOM problems.
