### ISSUE TITLE
Question: Where is the ./pretrained_ckpt folder?

### ISSUE THREAD

**Issue by DataJuggler** [GSeanCDAT/GIMM-VFI#5]
I read your instructions. I don't see a ./pretrained_ckpt folder after cloning. Where is this?

Am I supposed to create this folder? If yes, where do I create it?

Thanks

**Comment by GSeanCDAT** [comment]
Hi, you are supposed to create the ```pretrained_ckpt``` folder after cloning. Specifically, you can achieve this by the following command:
```
git clone https://github.com/GSeanCDAT/GIMM-VFI.git
cd GIMM-VFI
mkdir pretrained_ckpt
```
The ```pretrained_ckpt``` folder is supposed to be at the root directory of your cloned GIMM-VFI repo.

**Comment by DataJuggler** [comment]
Thank you. I will try this after work.
