### ISSUE TITLE
Question Are input frames supposed to be images or an .mp4?

### ISSUE THREAD

**Issue by DataJuggler** [GSeanCDAT/GIMM-VFI#7]
Your instructions are not very clear (or I am stupid). Do I need to export an mp4 as an image sequence, or can the path to frames be a path to an .mp4?

**Comment by proboot1** [comment]
yeah, you can use ffmpeg-7.1-full_build and divi up the video into imagens. 

ffmpeg -i "C:\\Users\\*****\\OneDrive\\Desktop\\GIMM-VFI-main\\NEWPROJ\\1.mp4" "D:\\New_output\\frame_%04d.png"
*****= your PC.. Also make sure you have the path set after installing it so you can use it call it..
